### ISSUE TITLE
Wildcard certificate

### ISSUE THREAD

**Issue by xpund** [lancard/nginx-webui#3]
Hi
We use your app and we really like it.
Especially after adding LogRotate
We are now manually adding wildcard certificates via console commands, but it seems to me that part of the process can be output to the web interface.
Do you think you will be able to do this in the near future?
If not, I could try it myself, but I'm afraid I don't have enough time for that.

Example command:
`certbot certonly --manual --preferred-challenges=dns --email admin@example.com --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.subdomain.example.com`

**Comment by lancard** [comment]
ok, i'll add that feature soon. :)

**Comment by lancard** [comment]
![image](https://github.com/lancard/nginx-webui/assets/42758339/45e0feac-4a3d-4ed5-9ec0-1a80a8081890)

feature added.

**Comment by lancard** [comment]
use 1.1.4
